### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by gtback** [TAXIIProject/django-taxii-services#30]
Django 1.7 does not support Python 2.6. We need to either ensure everything works in Django 1.6, or drop support for Python 2.6 (and require Python 2.7)

https://docs.djangoproject.com/en/dev/releases/1.7/#python-compatibility

**Comment by MarkDavidson** [comment]
Adding a comment here. I'm running into scenarios where RHEL (or a close relative of RHEL) is the preffered OS, and RHEL comes with python 2.6 (as mentioned). django-taxii-services requires python 2.7 because of `importlib`, which is a critical feature (It's how Message Handlers are dynamically loaded). So far, I've been using VirtualEnv to deploy YETI on RHEL (or similar) OSs. The CRITs guys have a pretty good writeup on VirtualEnv installation [1] that I've been using.

I can't remember what we specifically need in Django 1.7 (If anything). I'll have to do some research there. All I can recall is a `django.config()` (or something like that) call that's no longer used.

Thank you.
-Mark

[1] https://github.com/crits/crits/wiki/RHEL-Supplemental-Install-Guide

**Comment by gtback** [comment]
You can install `importlib` via [PyPI](https://pypi.python.org/pypi/importlib) on Python 2.6.

:+1: for virtualenvs in either case.

**Comment by hugovk** [comment]
Can this be closed?

Python 2.6 was dropped in https://github.com/TAXIIProject/django-taxii-services/commit/9c0e7d18344f1ea590cae72e10bd4494d663d3d4#diff-354f30a63fb0907d4ad57269548329e3.

This should be updated as well: https://github.com/TAXIIProject/django-taxii-services/blob/master/setup.py#L23-L24

**Comment by gtback** [comment]
yep, we can close this once setup.py is modified. Should be pretty quick.
